# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cryptoprices' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cryptoprices
  pod 'Alamofire'
  pod 'SwiftyJSON'

  target 'cryptopricesTests' do
    inherit! :search_paths
  end

end
